<script>
    top.idUsuario = '<?php echo $this->idUsuario; ?>';
</script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/js/rifas/rifas.js'; ?>"></script>
<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">

        <header>

            <ul class="breadcrumb"><!-- breadcrumb -->
                <li><a href="<?php echo $this->basePath() . '/cliente' ?>">Administração</a></li>
                <li class="active">Clientes</li>
                <li class="active">Cachês</li>
            </ul><!-- /breadcrumb -->

            <h2><!-- Page Title -->
                Controle de Cachês
            </h2><!-- /Page Title -->

        </header>

    </div>			
</section>
<!-- /PAGE TOP -->

<br />

<?php echo $this->partial('cad-rifas'); ?>
<?php echo $this->partial('psq-rifas'); ?>