<?php if (count($this->lista) > 0) : ?>
<?php //var_dump($this->lista); ?>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered" width="99%">
        <thead>
            <tr>
                <th width="10%" colspan="2"><span class="glyphicon glyphicon-cog"></span> Ações</th>
                <th>Instituição</th>
                <th width="45%">Prêmio(s)</th>
                <th>Sorteio</th>
                <th>Valor Rifa</th>
            </tr>
        </thead>
        <tbody>
            <?php if (isset($this->lista)) : ?>
                <?php foreach ($this->lista as $lista) : ?>
                    <tr>
                        <td style="text-align:center;">
                            <span onclick="selecionarRifas(<?php echo $lista['idRifa']; ?>);" title="Editar Rifa" class="glyphicon glyphicon-pencil" style="cursor: pointer;"></span>
                        </td>
                        <td style="text-align:center;">
                            <span onclick="confirmarExcluirRifas(<?php echo $lista['idRifa']; ?>);" title="Remover Rifa" class="glyphicon glyphicon-trash" style="cursor: pointer;"></span>
                        </td>
                        <td><?php echo $lista['dsInstituicao']; ?></td>
                        <td><?php echo $lista['dsPremio']; ?></td>
                        <td><?php echo $lista['dtSorteio']->format('d/m/Y'); ?></td>
                        <td><?php echo "R$ " . str_replace('.', ',', $lista['vlRifa']); ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->lista, 'Sliding', 'partials/paginator', array('url' => 'rifas/pesquisar/', 'parametros' => $this->parametros)); ?>
<?php endif; ?>

<?php if (count($this->lista) == 0) : ?>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered" width="99%">
        <tr>
            <td align="center">
                <strong>Nenhum registro foi encontrado!</strong>
            </td>
        </tr>
    </table>
    &nbsp;<br />&nbsp;<br />&nbsp;<br />&nbsp;
<?php endif; ?>