<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SGR ' . $this->translate('Sistema Gerenciador de Rifas'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/custom.css'))
                ->prependStylesheet($this->basePath('css/datepicker.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/bootstrap-datepicker.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/guiMoneyMask.js'))
        ;
        ?>

        <script type="text/javascript" src="<?php echo $this->basePath() . '/js/jsgeneralfunctions.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/js/componentes.js'; ?>"></script>
        <script type="text/javascript">
            top.basePath = '<?php echo $this->basePath(); ?>';
        </script>        

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Sistema Gerenciador de Rifas') ?></a>
                </div>
                    <?php if ($this->identity()) : ?>
                        <?php $tpUsuario = $this->identity()->getTpUsuario(); ?>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li id="menuHome" class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        </ul>
                        <?php if ($tpUsuario === 1) : ?>
                            <ul class="nav navbar-nav">
                                <li id="menuUsuario"><a href="<?php echo $this->url('usuario') ?>"><?php echo $this->translate('Usuários') ?></a></li>
                            </ul>
                        <?php endif; ?>
                        <ul class="nav navbar-right">
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="glyphicon glyphicon-user"></i> <?php echo $this->identity()->getNoUsuario(); ?>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="<?php echo $this->basePath(); ?>/login/logout"><i class="glyphicon glyphicon-off"></i> Sair</a>
                                    </li>
                                </ul>
                                <!-- /.dropdown-user -->
                            </li>
                            <!-- /.dropdown -->
                        </ul>
                        <!-- navbar-top-links -->
                    </div><!--/.nav-collapse -->
            <?php endif; ?>
            </div>
        </nav>
        <div class="container">
        <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Bruce Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>

        <div id="carregando" style="display: none;">
            <div id="conteudoCarregando">
                <div>
                    <i class="fa fa-spin fa-spinner"></i> Processando...
                </div>

                <div class="progress progress-striped active">
                    <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
                </div>
            </div>
        </div>

        <!-- Modal Alerta -->
        <div id="modalAlerta" style="display: none;" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalAlertaLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm" style="width: 35%;">
                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">×</span>
                            <span class="sr-only">Fechar</span>
                        </button>
                        <h4 class="modal-title" id="modalAlertaLabel">
                            <i class="glyphicon glyphicon-warning-sign"></i> Alerta
                        </h4>
                    </div>

                    <div class="modal-body">
                        <div class="row">

                            <div id="conteudoModalAlerta" style="color: #000000;"></div>

                            <div class="col-lg-6 col-md-6 center">
                                <button id="btnOk" type="submit" class="btn btn-primary">
                                    <i class="glyphicon glyphicon-ok"></i> Ok
                                </button>
                            </div>

                        </div>

                    </div>

                </div><!-- /.modal-content -->

            </div><!-- /.modal-dialog -->
        </div>
        <!-- Fim Modal -->

        <!-- Modal Confirmacao -->
        <div id="modalConfirmacao" style="display: none;" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalConfirmacaoLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm" style="width: 35%;">
                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">×</span>
                            <span class="sr-only">Fechar</span>
                        </button>
                        <h4 class="modal-title" id="modalConfirmacaoLabel">
                            <i class="glyphicon glyphicon-question-sign"></i> Confirmação
                        </h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">

                            <div id="conteudoModalConfirmacao" style="color: #000000;"></div>

                            <div class="col-lg-6 col-md-6" style="text-align: center;">
                                <button id="btnSim" type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-ok"></i> Sim</button>
                            </div>
                            <div class="col-lg-6 col-md-6" style="text-align: center;">
                                <button id="btnNao" type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> Não</button>
                            </div>

                        </div>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div>
        <!-- Fim Modal -->

    </body>
</html>
