<!-- CONTENT -->
<div id="cadUsuario">
    <!-- registration form -->
    <?php $formCadUsuario = $this->formCadUsuario; ?>
    <?php $formCadUsuario->prepare(); ?>

    <?php echo $this->form()->openTag($formCadUsuario); ?>
    
    <legend id="tituloUsuario"></legend>
    
    <?php echo $this->formElement($formCadUsuario->get('idUsuario')); ?>
    
    <div class="row">
        
        <div class="form-group col-md-6">
          <label class="control-label" for="login">Login:</label>
            <div class="input-group">
                <?php echo $this->formElement($formCadUsuario->get('login')); ?>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-user"></span>
                </span>
            </div>
        </div>
        
        <div class="form-group col-md-6">
          <label class="control-label" for="noUsuario">Nome:</label>
            <div class="input-group">
                <?php echo $this->formElement($formCadUsuario->get('noUsuario')); ?>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-pencil"></span>
                </span>
            </div>
        </div>
        
    </div>
    
    <div class="row">
        
        <div class="form-group col-md-12">
          <label class="control-label" for="email">Email:</label>
            <div class="input-group">
                <?php echo $this->formElement($formCadUsuario->get('email')); ?>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-envelope"></span>
                </span>
            </div>
        </div>
        
    </div>
    
    <div id="divSenha" class="row">
        
        <div class="form-group col-md-6">
            <label class="control-label" for="senha">Senha*:</label>
            <div class="input-group">
                <?php echo $this->formElement($formCadUsuario->get('senha')); ?>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-lock"></span>
                </span>
            </div>
        </div>
        
        <div class="form-group col-md-6">
            <label class="control-label" for="confirmarsenha">Confirmar Senha*:</label>
            <div class="input-group">
                <?php echo $this->formElement($formCadUsuario->get('confirmarsenha')); ?>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-lock"></span>
                </span>
            </div>
        </div>
        
    </div>
    
    
    <div class="row">
        
        <div class="form-group col-md-6">
            <label class="control-label" for="tpUsuario">Perfil:</label>
            <?php echo $this->formElement($formCadUsuario->get('tpUsuario')); ?>
        </div>
        
        <div class="form-group col-md-6">
            <label class="control-label" for="stUsuario">Situação:</label>
            <?php echo $this->formElement($formCadUsuario->get('stUsuario')); ?>
        </div>
        
    </div>
    
    <div class="row">
        <div class="form-group col-md-12">
            <?php echo $this->formButton()->openTag($formCadUsuario->get('btnNovoCad')); ?>
            <?php echo '<i class="glyphicon glyphicon-plus"></i> ' . $formCadUsuario->get('btnNovoCad')->getLabel(); ?>
            <?php echo $this->formButton()->closeTag(); ?>

            <?php echo $this->formButton()->openTag($formCadUsuario->get('btnGravar')); ?>
            <?php echo '<i class="glyphicon glyphicon-floppy-disk"></i> ' . $formCadUsuario->get('btnGravar')->getLabel(); ?>
            <?php echo $this->formButton()->closeTag(); ?>

            <?php echo $this->formButton()->openTag($formCadUsuario->get('btnVoltarCad')); ?>
            <?php echo '<i class="glyphicon glyphicon-arrow-left"></i> ' . $formCadUsuario->get('btnVoltarCad')->getLabel(); ?>
            <?php echo $this->formButton()->closeTag(); ?>
        </div>
    </div>
    
    <?php echo $this->form()->closeTag($formCadUsuario); ?>
    
</div>